name: Test Matriz Java on Push
run-name: ${{ github.actor }} ha realizado un cambio.

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: cd core && mvn clean compile

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: cd core && mvn clean compile

    - name: Run tests
      run: cd core && mvn test

    - name: Create Issue on Failure
      if: failure()
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "ERROR TEST en: ${{ github.workflow }} - ${{ github.event.head_commit.message }}"
        content-filepath: issue-body.md
        labels: "bug, automated issue"
